In [1]:
# reading the data and putting it in the dataframe formate

import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

file = 'train.csv'
train_data = pd.read_csv(file)
# print(df)
train_data.head()

df = pd.DataFrame(train_data)
df
# the number of rows is 1460!!

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [2]:
# checking the sum function to see if it works

# series = df.Series(df["Alley"])
# series.isnull.sum()
df["PoolQC"].isnull().sum()
# print(len(df["PoolQC"]))

1453

In [3]:
# showing uniqe values for each column to compare it to the same catigorical values after converting it.

# cols = list(train_data)

# for col in cols:
#     print(col)
#     print(df[col].unique())

In [4]:
# dropping columns with over 45% nan values. 

cols = list(train_data)

for col in cols:
#     print((df[col].isnull().sum()/1460))
    if (df[col].isnull().sum()/1460) > 0.35:
        print(col)
        train_data = train_data.drop(columns = col)
    print(df[col].isnull().sum())

0
0
0
259
0
0
Alley
1369
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
8
0
0
0
37
37
38
37
0
38
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
FireplaceQu
690
81
81
81
0
0
81
81
0
0
0
0
0
0
0
PoolQC
1453
Fence
1179
MiscFeature
1406
0
0
0
0
0
0

In [5]:
# printing unique values for each column to see the type of values in each column
# cols = list(train_data)

# for col in cols:
#     print(col)
#     print(df[col].unique())

In [6]:
df = pd.DataFrame(train_data)
df.head(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,IR1,Lvl,AllPub,Inside,...,0,320,0,0,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,IR1,Lvl,AllPub,Corner,...,228,0,0,0,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,Reg,Lvl,AllPub,Inside,...,205,0,0,0,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,IR2,Lvl,AllPub,Inside,...,0,0,176,0,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,IR1,Lvl,AllPub,Corner,...,176,0,0,0,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,IR1,Lvl,AllPub,CulDSac,...,0,0,0,0,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,5,2009,COD,Abnorml,139000

In [7]:
# cols = list(train_data)

# for col in cols:
#     if col == 'GarageQual' or col == 'GarageCond':
#         print(col)
#         print(df['GarageQual'])
#         print(df['GarageCond'])

In [8]:
# in this cell we check for each column if its empty. If it is, we fill categorical data with median value and  
# numerical ones with average value of the column

cols = list(train_data)

for col in cols:
    if (df[col].isnull().sum()) > 1:
        if isinstance(train_data[col][1], str) :
            train_data.fillna(train_data[col].median(), inplace = True)
        else: 
            train_data.fillna(train_data[col].median(), inplace = True)

In [9]:
# in this step, we will remove columns with values that are mostly zeros before converting catigorical data 
# into numerical ones. 

# first we check which columns have values that are mostly zeros

for col in cols:
#     print(col)
#     print(df[col].unique())
    if ( (df[col].astype(bool).sum(axis=0)/1460) < 0.40 ): # if the number of the non-zero value is less than 40%
        print(col)
        train_data = train_data.drop(columns = col)

BsmtFinSF2
LowQualFinSF
BsmtHalfBath
HalfBath
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
MiscVal

In [10]:
# before this step fill in missing values.
# Now we turn catigorical values into numerical values


# train_data['MSZoning'] = train_data['MSZoning'].astype('category').cat.codes

cols = list(train_data)

for col in cols:
    if isinstance(train_data[col][1], str) :
        train_data[col] = train_data[col].astype('category').cat.codes
        
df = pd.DataFrame(train_data)
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,5,5,2,0,61,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,5,5,2,298,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,5,5,2,0,42,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,5,5,2,0,35,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,5,5,2,192,84,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,3,3,0,4,...,5,5,2,0,40,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,3,3,0,4,...,5,5,2,349,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,3,3,0,4,...,5,5,2,0,60,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,3,3,0,4,...,5,5,2,366,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,3,3,0,4,...,5,5,2,736,68,6,2008,8,4,147500

In [11]:
# checking to see if all of Nan values have been removed.

for col in cols:
    print(df[col].isnull().sum())

# it works!!

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [12]:
df.head(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,5,5,2,0,61,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,5,5,2,298,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,5,5,2,0,42,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,5,5,2,0,35,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,5,5,2,192,84,12,2008,8,4,250000
5,6,50,3,85.0,14115,1,0,3,0,4,...,5,5,2,40,30,10,2009,8,4,143000
6,7,20,3,75.0,10084,1,3,3,0,4,...,5,5,2,255,57,8,2007,8,4,307000
7,8,60,3,69.0,10382,1,0,3,0,0,...,5,5,2,235,204,11,2009,8,4,200000
8,9,50,4,51.0,6120,1,3,3,0,4,...,2,5,2,90,0,4,2008,8,0,129900
9,10,190,3,50.0,7420,1,3,3,0,0,...,3,5,2,0,4,1,2008,8,4,118000
10,11,20,3,70.0,11200,1,3,3,0,4,...,5,5,2,0,0,2,2008,8,4,129500
11,12,60,3,85.0,11924,1,0,3,0,4,...,5,5,2,147,21,7,2006,6,5,345000
12,13,20,3,69.0,12968,1,1,3,0,4,...,5,5,2,140,0,9,2008,8,4,144000
13,14,20,3,91.0,10652,1,0,3,0,4,...,5,5,2,160,33,8,2007,6,5,279500
14,15,20,3,69.0,10920,1,0,3,0,0,...,5,5,2,0,213,5,2008,8,4,157000
15,16,45,4,51.0,6120,1,3,3,0,0,...,5,5,2,48,112,7,2007,8,4,132000
16,17,20,3,69.0,11241,1,0,3,0,1,...,5,5,2,0,0,3,2010,8,4,149000
17,18,90,3,72.0,10791,1,3,3,0,4,...,5,5,2,0,0,10,2006,8,4,90000
18,19,20,3,66.0,13695,1,3,3,0,4,...,5,5,2,0,102,6,2008,8,4,159000
19,20,20,3,70.0,7560,1,3,3,0,4,...,5,5,2,0,0,5,2009,0,0,139000

In [13]:
# it seems that some columns like 'poolArea' have many 0 values, maybe remove those too? it was removed. 
cols = list(train_data)
print(cols)

['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'BsmtFullBath', 'FullBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

In [14]:
# df.corr()
# fig, ax = plt.subplots(figsize=(40,40))
# sns.heatmap(df.corr(), annot=True, linewidth=.5, ax=ax)
# plt.show()

In [23]:
import numpy as np
print(train_data['OverallQual'])
X = np.asarray(train_data[["OverallQual", "YearBuilt", "YearRemodAdd", "MasVnrArea", "TotalBsmtSF", "1stFlrSF", "GrLivArea", "FullBath", "TotRmsAbvGrd", "Fireplaces", "GarageCars" ,"GarageArea"]])
Y = train_data['SalePrice']
print(X)

0       7
1       6
2       7
3       7
4       8
       ..
1455    6
1456    6
1457    7
1458    5
1459    5
Name: OverallQual, Length: 1460, dtype: int64
[[7.000e+00 2.003e+03 2.003e+03 ... 0.000e+00 2.000e+00 5.480e+02]
 [6.000e+00 1.976e+03 1.976e+03 ... 1.000e+00 2.000e+00 4.600e+02]
 [7.000e+00 2.001e+03 2.002e+03 ... 1.000e+00 2.000e+00 6.080e+02]
 ...
 [7.000e+00 1.941e+03 2.006e+03 ... 2.000e+00 1.000e+00 2.520e+02]
 [5.000e+00 1.950e+03 1.996e+03 ... 0.000e+00 1.000e+00 2.400e+02]
 [5.000e+00 1.965e+03 1.965e+03 ... 0.000e+00 1.000e+00 2.760e+02]]

In [20]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

Scaler = MinMaxScaler()

xTrain, xTest, yTrain, yTest = train_test_split(X, Y, test_size=0.15)
print(xTest)
print()
xTrain = Scaler.fit_transform(xTrain)
xTest = Scaler.transform(xTest)
print(xTest)

4       250000
235      89500
674     140000
390     119000
1382    157000
         ...
976      85500
471     190000
939     244400
368     132000
1082    192000
Name: SalePrice, Length: 219, dtype: int64

4       250000
235      89500
674     140000
390     119000
1382    157000
         ...
976      85500
471     190000
939     244400
368     132000
1082    192000
Name: SalePrice, Length: 219, dtype: int64

In [24]:
import statsmodels.api as sm

model = sm.OLS(yTrain, xTrain).fit()
predictions = model.predict(xTest) # make the predictions by the model

# Print out the statistics
model.summary()

ModuleNotFoundError: No module named 'statsmodels'